import { toMovieEntity } from "../entities/movie.entity.js";

function createSeedMovies() {
    const seedMovies = [
        {
            id: 1,
            title: 'The Dark Horizon',
            genre: 'Sci-Fi',
            rating: 'PG-13',
            description: 'In a dystopian future where humanity has colonized the outer planets, a lone pilot discovers a signal from a long-lost Earth that could change everything. With stunning visuals and a gripping narrative, this sci-fi epic explores the boundaries of human ambition and the cost of survival.',
            poster: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['2:00 PM', '5:00 PM', '8:00 PM'],
            duration: '2h 15m',
            director: 'James Nolan',
            cast: ['Chris Evans', 'Zoe Saldana', 'Oscar Isaac'],
        },
        {
            id: 2,
            title: 'Midnight in Paris',
            genre: 'Romance',
            rating: 'PG',
            description: 'A young couple on their honeymoon in Paris finds themselves magically transported to the 1920s, where they meet legendary artists and writers. A heartwarming tale of love, nostalgia, and the magic of the city of lights.',
            poster: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['1:00 PM', '4:00 PM', '7:00 PM'],
            duration: '1h 54m',
            director: 'Sofia Laurent',
            cast: ['Emma Stone', 'Ryan Gosling', 'Marion Cotillard'],
        },
        {
            id: 3,
            title: 'Shadow Protocol',
            genre: 'Action',
            rating: 'R',
            description: 'A retired CIA agent is pulled back into the world of espionage when a former ally goes rogue, threatening global security. Packed with intense action sequences and unexpected twists, this thriller keeps you on the edge of your seat.',
            poster: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['3:00 PM', '6:00 PM', '9:00 PM'],
            duration: '2h 5m',
            director: 'Michael Bay',
            cast: ['Tom Hardy', 'Charlize Theron', 'Idris Elba'],
        },
        {
            id: 4,
            title: 'The Last Laugh',
            genre: 'Comedy',
            rating: 'PG-13',
            description: "Two estranged brothers reunite for their father's funeral, only to discover he's left behind a series of hilarious challenges they must complete together to claim their inheritance. A feel-good comedy about family, forgiveness, and finding humor in life.",
            poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['12:00 PM', '3:30 PM', '7:00 PM'],
            duration: '1h 48m',
            director: 'Adam McKay',
            cast: ['Will Ferrell', 'John C. Reilly', 'Tina Fey'],
        },
        {
            id: 5,
            title: 'Whispers in the Dark',
            genre: 'Horror',
            rating: 'R',
            description: 'A family moves into a seemingly perfect Victorian home, only to uncover the horrifying secrets buried within its walls. As supernatural events escalate, they must confront the evil that lurks in every shadow before it consumes them.',
            poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['5:30 PM', '8:30 PM', '11:00 PM'],
            duration: '1h 52m',
            director: 'Ari Aster',
            cast: ['Florence Pugh', 'Jack Reynor', 'William Defoe'],
        },
        {
            id: 6,
            title: "Ocean's Legacy",
            genre: 'Drama',
            rating: 'PG-13',
            description: 'An aging marine biologist embarks on one final expedition to document the migration of blue whales, reflecting on a lifetime of discovery and the oceans he fought to protect. A visually stunning and emotionally powerful drama.',
            poster: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'currently_running',
            showtimes: ['1:30 PM', '4:30 PM', '7:30 PM'],
            duration: '2h 10m',
            director: 'Denis Villeneuve',
            cast: ['Anthony Hopkins', 'Cate Blanchett', 'Dev Patel'],
        },
        {
            id: 7,
            title: 'Galactic Siege',
            genre: 'Sci-Fi',
            rating: 'PG-13',
            description: "When an alien armada threatens Earth, a ragtag team of scientists and soldiers must use untested technology to mount humanity's last defense. An explosive space opera with breathtaking visual effects.",
            poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'coming_soon',
            showtimes: ['2:00 PM', '5:00 PM', '8:00 PM'],
            duration: '2h 25m',
            director: 'Christopher Nolan',
            cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki'],
        },
        {
            id: 8,
            title: 'The Art of Deception',
            genre: 'Thriller',
            rating: 'R',
            description: "A master art forger is hired by a mysterious collector to steal the world's most famous painting, but the heist takes a deadly turn when he realizes the true motive behind the theft. A stylish and suspenseful crime thriller.",
            poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'coming_soon',
            showtimes: ['3:00 PM', '6:30 PM', '9:30 PM'],
            duration: '2h 0m',
            director: 'David Fincher',
            cast: ['Michael Fassbender', 'Tilda Swinton', 'Tim Blake Nelson'],
        },
        {
            id: 9,
            title: 'Legends of the Wild',
            genre: 'Animation',
            rating: 'G',
            description: 'A young fox sets out on a journey across enchanted forests to find the legendary Golden Acorn that can save her family. A beautifully animated adventure filled with humor, heart, and unforgettable characters.',
            poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'coming_soon',
            showtimes: ['11:00 AM', '1:30 PM', '4:00 PM'],
            duration: '1h 40m',
            director: 'Hayao Miyazaki',
            cast: ['Daisy Ridley', 'Awkwafina', 'Keegan-Michael Key'],
        },
        {
            id: 10,
            title: 'Broken Chains',
            genre: 'Drama',
            rating: 'R',
            description: 'Based on a true story, a wrongfully imprisoned man spends decades fighting for justice while forming an unlikely bond with a guard who believes in his innocence. A powerful and moving drama about resilience and the human spirit.',
            poster: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
            trailerUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            status: 'coming_soon',
            showtimes: ['2:30 PM', '5:30 PM', '8:30 PM'],
            duration: '2h 30m',
            director: 'Steve McQueen',
            cast: ['Daniel Kaluuya', 'Viola Davis', 'Mahershala Ali'],
        },
    ];

    return seedMovies.map(toMovieEntity);
}

export { createSeedMovies };
